version: '3'
services: 
    build-image:
        image: lqxx-image
        build: .
    backend:
        image: lqxx-image
        volumes: 
            - ../:/workspaces/lqxx
        ports: 
            - 3001:3001
        depends_on:
            - build-image
        command: >
            bash -c " git submodule update --init;
                      mkdir build;
                      cd build;
                      cmake .. &&
                      make &&
                      ./lqxx "
    backend-test-api:
        image: lqxx-image
        volumes: 
            - ../:/workspaces/lqxx
        depends_on:
            - build-image
        command: >
            bash -c " git submodule update --init;
                      mkdir build;
                      cd build;
                      cmake .. &&
                      make &&
                      ./api/test_api "
    backend-test-tasklist:
        image: lqxx-image
        volumes: 
            - ../:/workspaces/lqxx
        depends_on:
            - build-image
        command: >
            bash -c " git submodule update --init;
                      mkdir build;
                      cd build;
                      cmake .. &&
                      make &&
                      ./tasklists/test_tasklists"
    backend-test-task:
        image: lqxx-image
        volumes: 
            - ../:/workspaces/lqxx
        depends_on:
            - build-image
        command: >
            bash -c " git submodule update --init;
                      mkdir build;
                      cd build;
                      cmake .. &&
                      make &&
                      ./tasks/test_tasks"
    bash:
        image: lqxx-image
        volumes: 
            - ../:/workspaces/lqxx
        ports: 
            - 3001:3001
        depends_on:
            - build-image
        stdin_open: true
        tty: true
        command: /bin/bash