name: api-unit-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: main test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: git config --global --add safe.directory /workspaces/lqxx && rm -rf external/cpp-jwt external/googletest external/json external/liboauthcpp && cd deploy && docker-compose run backend-test