name: DB-unit-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'db/**'
  push:
    branches:
      - main
    paths:
      - 'db/**'
jobs:
  run-test-db:
    runs-on: ubuntu-latest
    steps:
    - name: Install GTest manually
      run: git clone https://github.com/google/googletest.git -b release-1.12.1 && cd googletest && mkdir build && cd build && cmake .. && make && sudo make install
    - name: Install neo4j
      run: sudo apt install neo4j && neo4j-admin set-initial-password hello4156 && sudo service neo4j start
    - uses: actions/checkout@v3
    - name: Build the DB source
      run: cd db && mkdir build && cd build && cmake .. && make
    - name: Run test
      run: /home/runner/work/lqxx4156/lqxx4156/db/build/DBTest
