name: DB-unit-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'db/**'
  push:
    branches:
      - main
    paths:
      - 'db/**'
jobs:
  run-test-db:
    runs-on: ubuntu-latest
    steps:
    - name: Install GTest manually
      run: git clone https://github.com/google/googletest.git -b release-1.12.1 && cd googletest && mkdir build && cd build && cmake .. && make && sudo make install
    - name: Install mongoDB
      run: wget https://github.com/mongodb/mongo-c-driver/releases/download/1.23.0/mongo-c-driver-1.23.0.tar.gz && tar xzf mongo-c-driver-1.23.0.tar.gz && cd mongo-c-driver-1.23.0 && mkdir build && cd build && cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .. && cmake --build . && sudo cmake --build . --target install
    - uses: actions/checkout@v3
    - name: Build the DB source
      run: cd db && mkdir build && cd build && cmake .. && make
    - name: Run test
      run: /home/runner/work/lqxx4156/lqxx4156/db/build/DBTest
