name: DB-unit-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'db/**'
  push:
    branches:
      - main
    paths:
      - 'db/**'
jobs:
  run-test-db:
    runs-on: ubuntu-latest
    steps:
    - name: Install GTest manually
      run: git clone https://github.com/google/googletest.git -b release-1.12.1 && cd googletest && mkdir build && cd build && cmake .. && make && sudo make install
    - name: Install libneo4j-client
      run: sudo apt-get install libcypher-parser-dev libedit-dev && git clone https://github.com/cleishm/libneo4j-client.git && cd libneo4j-client && ./autogen.sh && ./configure && make clean check && sudo make install
    - name: Install Java 11
      run: sudo apt-get install openjdk-11-jre
    - name: Install neo4j
      run: wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add - && echo 'deb https://debian.neo4j.com stable latest' | sudo tee -a /etc/apt/sources.list.d/neo4j.list && sudo apt-get update && sudo apt install neo4j && sudo neo4j-admin set-initial-password hello4156
    - name: Run neo4j
      run:  sudo systemctl start neo4j && sleep 10
    - uses: actions/checkout@v3
    - name: Build the DB source
      run: cd db && mkdir build && cd build && cmake .. && make
    - name: Run test
      run: /home/runner/work/lqxx4156/lqxx4156/db/build/DBTest
