name: tasklist-unit-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'tasklists/**'
  push:
    branches:
      - main
    paths:
      - 'tasklists/**'
jobs:
  test:
    name: main test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Run tests
      run: cd deploy && docker-compose run backend-test-tasklist

