name: tasklist-unit-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    name: main test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: cd deploy && docker-compose run backend-test-tasklist
    
    - name: Clean up
      run: docker-compose down
